[project]
name = "amor-ontologies"
version = "0.1.0"
description = "Code used in the generation and testing of the ontologies"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyld>=2.0.4",
    "pytest>=8.3.4",
    "rdflib>=7.1.3",
    "requests>=2.32.3",
]
