prefix amor-bhv: <http://www.gsi.upm.es/ontologies/amor/models/bhv/ns#>
prefix amor-data: <http://www.gsi.upm.es/ontologies/amor/datasets/ns#>
prefix amor-data-examples: <http://www.gsi.upm.es/ontologies/amor/datasets/examples#>
prefix amor-exp: <http://www.gsi.upm.es/ontologies/amor/experiments/ns#>
prefix ex-exp: <http://www.gsi.upm.es/ontologies/amor/experiments/examples#>
prefix amor-graph: <http://amor-graph.gsi.upm.es/ns#>
prefix amor: <http://www.gsi.upm.es/ontologies/amor/ns#>
prefix amor-mft: <http://www.gsi.upm.es/ontologies/amor/models/mft/ns#>
prefix bhv: <http://www.gsi.upm.es/ontologies/bhv/ns#>
prefix dc: <http://purl.org/dc/terms/>
prefix marl: <http://www.gsi.upm.es/ontologies/marl/ns#>
prefix mft: <http://www.gsi.upm.es/ontologies/mft/ns#>
prefix mls: <http://www.w3.org/ns/mls#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
prefix onyx: <http://www.gsi.upm.es/ontologies/onyx/ns#>
prefix oro: <http://kb.openrobots.org#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix sebb: <http://www.gsi.upm.es/ontologies/sebb/ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix vann: <http://purl.org/vocab/vann/>
prefix wnaffect: <http://gsi.upm.es/ontologies/wnaffect/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix oa: <http://www.w3.org/ns/oa#>
prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#>
